# Generated by Django 3.0 on 2022-12-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221217_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AddField(
            model_name='player',
            name='location_lat',
            field=models.CharField(default='latl', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='location_long',
            field=models.CharField(default='long', max_length=255),
            preserve_default=False,
        ),
    ]
