# Generated by Django 3.0 on 2022-12-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20221220_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='auth',
            field=models.TextField(blank=True),
        ),
    ]
