# Generated by Django 3.0 on 2022-12-26 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rule_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='submanager',
            name='club_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team_members',
            name='team_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='number_stad',
            field=models.IntegerField(default=0),
        ),
    ]
