# Generated by Django 3.0 on 2022-12-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20221227_1343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserType',
            new_name='UserRate',
        ),
    ]
