# Generated by Django 3.0 on 2022-12-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20221227_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='caneled',
            new_name='canceled',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
