# Generated by Django 3.0 on 2022-12-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20221228_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrate',
            old_name='rateType_id',
            new_name='rate_type_id',
        ),
    ]
