# Generated by Django 3.0 on 2023-01-04 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20221228_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='location',
            new_name='location_lat',
        ),
        migrations.RenameField(
            model_name='stadiumrate',
            old_name='value',
            new_name='percent',
        ),
        migrations.AddField(
            model_name='club',
            name='location_long',
            field=models.CharField(default='lat', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=30)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user11', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user22', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
