# Generated by Django 3.0 on 2023-01-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_friend_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='search_game',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='temp',
            field=models.BooleanField(default=False),
        ),
    ]
