# Generated by Django 3.0 on 2023-01-16 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20230116_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_members',
            name='position_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Position'),
        ),
    ]
