# Generated by Django 3.0 on 2023-01-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_team_member_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_members',
            name='is_captin',
            field=models.BooleanField(default=False),
        ),
    ]
