# Generated by Django 3.0 on 2023-02-01 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20230121_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rule_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('group message', 'group message'), ('freind message', 'freind message'), ('request friend', 'request friend'), ('accept friend', 'accept friend')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='team_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
        migrations.DeleteModel(
            name='permission',
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
