# Generated by Django 3.0 on 2023-02-25 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.IntegerField(unique=True)),
                ('client_ammunt', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammunt', models.FloatField()),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank.Operation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank.Account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='client_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank.ClientType'),
        ),
    ]
