# Generated by Django 3.0 on 2023-02-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='client_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
