# Generated by Django 3.0 on 2023-02-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_auto_20230225_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='client_ammunt',
            field=models.FloatField(default=0),
        ),
    ]
