# Generated by Django 4.1.1 on 2022-10-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0002_petmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="petmodel",
            name="name",
            field=models.CharField(default="popy", max_length=55),
        ),
    ]
